layout_spectrum: 0.8378868818732144
typography_spectrum: 0.41894561612121023
color:
  brandColors:
    - '#88A825'
    - '#35203B'
    - '#911146'
    - '#CF4A30'
    - '#ED8C2B'
  brandStrength: 0.22820802182355657
  lightness: 0.11008900260257691
  saturation: 0.10737240385162727
  rhythmicContrast: 0.12787792077961166
coverPrefs:
  filter: false
name: Mardi' Gras
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/19eb8899-5220-40a9-93db-b2f5d1e81cfc.png
opengraph:
  type: ''
  appId: ''
purpose:
  - type: contact
    label: Contact Mardi' Gras
    url: 'mailto:cdrandassociates@yahoo.com'
title: ''
description: Southern Creole Restaurant & Lounge
author:
  name: Samson Slater
  url: 'http//:thegrid.ai/bam@bam-com'
  email: dlpshows@gmail.com
content_rating:
  adult: false
content: []
github: true
